### ISSUE TITLE
building on macosx fails: tempo.c built to priv/tempo_drv.so

### ISSUE THREAD

**Issue by llaisdy** [selectel/tempo#7]
Dear All

The title says it all.  Here's the eunit output:

```
======================== EUnit ========================
undefined
*** test module not found ***
**tempo


=ERROR REPORT==== 11-Dec-2012::15:54:34 ===
The on_load function for module tempo returned {error,
                                                {load_failed,
                                                 "Failed to load NIF library: 'dlopen(/Users/ivan/local/erlang/tempo_git/priv/tempo.so, 2): image not found'"}}
=======================================================
```

Attempting to run tempo fails with the same error.  A symlink from priv/tempo.so to priv/tempo_drv.so makes everything ok.

I wonder if this is something to do with the rebar port compiler and compiling on macosx.  I'e had a quick scan through rebar and google but not turned up anything.

(Apart from that, tempo is a /very/ handy piece of code!)

Best wishes

Ivan

**Comment by superbobry** [comment]
I wonder if this is still the case?

**Comment by tnt-dev** [comment]
281e1c7860b9611d1aaa014b8d19ac5d5d9b5207 and eb240f8684b90a59e8bd51211c7d7936b0cf205c
